name: Pages

on:
  push:
    branches:
      - main # default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Key
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "RolinShmily@outlook.com"
          git config --global user.name "RolinShmily"
      
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: main
          submodules: recursive
      
      - name: Use Node.js 23
        uses: actions/setup-node@v4
        with:
          node-version: '23'
      
      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-
      
      - name: Install Dependencies
        run: |
          npm install hexo-cli -g
          npm install
      
      - name: Build
        run: |
          hexo clean
          hexo generate
      
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
  
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  refresh-cdn:
    needs: deploy  
    runs-on: ubuntu-latest
    steps:
      - name: 阿里云 CDN 缓存刷新
        env:
          ALIYUN_ACCESS_KEY_ID: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          ALIYUN_ACCESS_KEY_SECRET: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
          REFRESH_PATH: ${{ secrets.REFRESH_PATH }}
        run: |
          # 构造基础请求参数
          params="Action=RefreshObjectCaches&Format=JSON&Version=2018-05-10"
          params+="&AccessKeyId=${ALIYUN_ACCESS_KEY_ID}"
          params+="&SignatureMethod=HMAC-SHA1"
          params+="&SignatureVersion=1.0"
          params+="&SignatureNonce=$(date +%s%N)" # 生成唯一随机数
          params+="&Timestamp=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" # UTC 时间
          params+="&ObjectPath=${REFRESH_PATH}"
          params+="&ObjectType=Directory" # 按目录刷新，可按需改为 File 等
          params+="&Force=true" # 强制删除缓存

          # 生成签名：按阿里云 API 规范，对请求参数排序、编码后生成
          sorted_params=$(echo $params | tr '&' '\n' | sort | tr '\n' '&' | sed 's/&$//')
          string_to_sign="POST&%2F&$(echo -n $sorted_params | awk -F'&' '{for(i=1;i<=NF;i++){printf "%s&", $i}}' | sed 's/&$//' | xxd -plain | tr -d '\n' | sed 's/\(..\)/%\1/g')"
          signature=$(echo -n "$string_to_sign" | openssl dgst -sha1 -hmac "${ALIYUN_ACCESS_KEY_SECRET}&" -binary | openssl enc -base64)

          # 发起 POST 请求调用阿里云 CDN 接口
          curl -X POST "https://cdn.aliyuncs.com/?${sorted_params}&Signature=${signature}" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -H "User-Agent: GitHub-Actions-CDN-Refresh"
